// === budget.js ===
// Adds "Monthly Budget" button and handles PDF generation

document.addEventListener("DOMContentLoaded", () => {
  const container = document.querySelector(".box");

  // --- Create new UI elements ---
  const budgetBtn = document.createElement("button");
  budgetBtn.innerText = "💰 Monthly Budget";
  budgetBtn.classList.add("notice-btn");
  budgetBtn.style.backgroundColor = "#ff9800";
  budgetBtn.style.marginTop = "10px";

  const monthSelect = document.createElement("select");
  monthSelect.id = "budgetMonth";
  monthSelect.style.display = "none";
  monthSelect.style.marginTop = "10px";
  monthSelect.innerHTML = `
    <option value="">Select Month</option>
    <option value="01">January</option>
    <option value="02">February</option>
    <option value="03">March</option>
    <option value="04">April</option>
    <option value="05">May</option>
    <option value="06">June</option>
    <option value="07">July</option>
    <option value="08">August</option>
    <option value="09">September</option>
    <option value="10">October</option>
    <option value="11">November</option>
    <option value="12">December</option>
  `;

  // Add to DOM
  container.appendChild(budgetBtn);
  container.appendChild(monthSelect);

  // --- Handle button click ---
  budgetBtn.addEventListener("click", () => {
    if (monthSelect.style.display === "none") {
      monthSelect.style.display = "block";
    } else {
      const month = monthSelect.value;
      if (!month) {
        alert("⚠️ Please select a month first.");
        return;
      }
      generateBudgetPDF(month);
    }
  });
});

// --- Generate Monthly Budget PDF ---
function generateBudgetPDF(month) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const monthNames = {
    "01": "January",
    "02": "February",
    "03": "March",
    "04": "April",
    "05": "May",
    "06": "June",
    "07": "July",
    "08": "August",
    "09": "September",
    "10": "October",
    "11": "November",
    "12": "December"
  };

  const data = [
    ["0001", "Basic Pay", "75,530.00"],
    ["1000", "House Rent Allowance", "2,727.00"],
    ["1210", "Convey Allowance", "5,000.00"],
    ["1300", "Medical Allowance", "1,500.00"],
    ["1530", "Hill Allowance", "200.00"],
    ["1838", "Teaching Allowance", "750.00"],
    ["2318", "Disparity Reduction Allowance 25%", "4,728.00"]
  ];

  // --- Calculate total ---
  let total = 0;
  data.forEach(row => {
    total += parseFloat(row[2].replace(/,/g, ""));
  });

  // --- Header ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(
    `Sardar Shah Mohammad Khan Late Govt. Boys High School Ghel Topi, Bagh`,
    105,
    20,
    { align: "center" }
  );

  doc.setFontSize(12);
  doc.text(`Monthly Budget - ${monthNames[month]} 2025`, 105, 30, { align: "center" });
  doc.line(20, 35, 190, 35);

  // --- Table ---
  doc.autoTable({
    startY: 45,
    head: [["Wage Type", "Description", "Total (Rs)"]],
    body: data,
    styles: { halign: "center", fontSize: 10 },
    headStyles: { fillColor: [0, 74, 173] }
  });

  const finalY = doc.lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "bold");
  doc.text(`Total: Rs ${total.toLocaleString()}`, 150, finalY, { align: "right" });

  // --- Footer ---
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by IT Center Ghel Topi", 105, 285, { align: "center" });

  // --- Save ---
  doc.save(`Monthly_Budget_${month}_2025.pdf`);
}
